import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { createJournalEntry, deleteJournalEntry, getJournalEntries } from '../services/tripApi';
import ScreenHeader from '../components/ScreenHeader';
import { colors, spacing } from '../theme';

export default function JournalScreen() {
  const [entries, setEntries] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title: '', date: '', location: '', mood: 'Happy', description: '' });
  useEffect(() => { const load = async () => { try { setEntries(await getJournalEntries()); } catch { setError('Unable to load your journal.'); } finally { setIsLoading(false); } }; void load(); }, []);
  const save = async () => { try { const saved = await createJournalEntry(form); setEntries((current) => [saved, ...current]); setForm({ title: '', date: '', location: '', mood: 'Happy', description: '' }); setShowForm(false); } catch { setError('Unable to save this entry.'); } };
  const remove = async (id) => { try { await deleteJournalEntry(id); setEntries((current) => current.filter((entry) => entry.id !== id)); } catch { setError('Unable to delete this entry.'); } };
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.headerRow}><ScreenHeader eyebrow="YOUR TRAVEL DIARY" title="Journal" subtitle="Keep the details that made the day yours." /><Pressable style={styles.addButton} onPress={() => setShowForm((current) => !current)}><Text style={styles.addText}>{showForm ? 'Close' : '+ Entry'}</Text></Pressable></View>{showForm && <View style={styles.form}><TextInput style={styles.input} placeholder="Title" value={form.title} onChangeText={(value) => setForm((current) => ({ ...current, title: value }))} /><TextInput style={styles.input} placeholder="Location" value={form.location} onChangeText={(value) => setForm((current) => ({ ...current, location: value }))} /><TextInput style={styles.input} placeholder="Date (YYYY-MM-DD)" value={form.date} onChangeText={(value) => setForm((current) => ({ ...current, date: value }))} /><TextInput style={styles.input} placeholder="Your story" multiline value={form.description} onChangeText={(value) => setForm((current) => ({ ...current, description: value }))} /><Pressable style={styles.primaryButton} onPress={save}><Text style={styles.primaryText}>Save Entry</Text></Pressable></View>}{isLoading && <ActivityIndicator color={colors.green} />}{error && <Text style={styles.error}>{error}</Text>}{!isLoading && !error && entries.length === 0 && <Text style={styles.empty}>Your first story is waiting to be written.</Text>}{entries.map((entry) => <View style={styles.card} key={entry.id}><Text style={styles.meta}>{entry.date}  ·  {entry.location}</Text><Text style={styles.title}>{entry.title}</Text><Text style={styles.mood}>{entry.mood}</Text><Text style={styles.description}>{entry.description}</Text><Pressable onPress={() => remove(entry.id)}><Text style={styles.delete}>Delete entry</Text></Pressable></View>)}</ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: spacing.page, paddingTop: 58, backgroundColor: colors.sand, flexGrow: 1 }, headerRow: { position: 'relative' }, addButton: { position: 'absolute', right: 0, top: 0, padding: 10, borderRadius: 20, backgroundColor: colors.green }, addText: { color: '#fff', fontSize: 11, fontWeight: '800' }, form: { padding: spacing.card, marginBottom: 16, borderRadius: 14, backgroundColor: colors.paper }, input: { padding: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.line, borderRadius: 7, backgroundColor: '#fff' }, primaryButton: { alignItems: 'center', padding: 12, borderRadius: 7, backgroundColor: colors.green }, primaryText: { color: '#fff', fontWeight: '800' }, card: { padding: spacing.card, marginBottom: spacing.medium, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.paper }, meta: { color: colors.muted, fontSize: 11 }, title: { color: colors.ink, fontSize: 20, fontWeight: '800', marginTop: 9 }, mood: { color: colors.green, fontSize: 12, marginTop: 7 }, description: { color: colors.muted, fontSize: 13, lineHeight: 21, marginTop: 11 }, delete: { color: '#a65748', fontSize: 11, marginTop: 12 }, error: { color: '#a65748' }, empty: { color: colors.muted, fontSize: 14 }, });
