import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { createMemory, deleteMemory, getMemories } from '../services/tripApi';
import ScreenHeader from '../components/ScreenHeader';
import { colors, spacing } from '../theme';

export default function MemoriesScreen() {
  const [memories, setMemories] = useState([]);
  const [isLoading, setIsLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ image: '', title: '', location: '', date: '', description: '' });
  useEffect(() => { const load = async () => { try { setMemories(await getMemories()); } finally { setIsLoading(false); } }; void load(); }, []);
  const save = async () => { try { const saved = await createMemory(form); setMemories((current) => [saved, ...current]); setForm({ image: '', title: '', location: '', date: '', description: '' }); setShowForm(false); } catch { /* The empty form remains visible for correction. */ } };
  const remove = async (id) => { try { await deleteMemory(id); setMemories((current) => current.filter((memory) => memory.id !== id)); } catch { /* Keep the card when the server rejects deletion. */ } };
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.headerRow}><ScreenHeader eyebrow="YOUR COLLECTION" title="MemoryGram" subtitle="Your journey, captured in moments." /><Pressable style={styles.addButton} onPress={() => setShowForm((current) => !current)}><Text style={styles.addText}>{showForm ? 'Close' : '+ Memory'}</Text></Pressable></View>{showForm && <View style={styles.form}><TextInput style={styles.input} placeholder="Image URL" value={form.image} onChangeText={(value) => setForm((current) => ({ ...current, image: value }))} /><TextInput style={styles.input} placeholder="Title" value={form.title} onChangeText={(value) => setForm((current) => ({ ...current, title: value }))} /><TextInput style={styles.input} placeholder="Location" value={form.location} onChangeText={(value) => setForm((current) => ({ ...current, location: value }))} /><TextInput style={styles.input} placeholder="Date (YYYY-MM-DD)" value={form.date} onChangeText={(value) => setForm((current) => ({ ...current, date: value }))} /><Pressable style={styles.primaryButton} onPress={save}><Text style={styles.primaryText}>Save Memory</Text></Pressable></View>}{isLoading && <ActivityIndicator color={colors.green} />}{!isLoading && memories.length === 0 && <Text style={styles.empty}>Add a memory from the web app to see it here.</Text>}<View style={styles.grid}>{memories.map((memory) => <View style={styles.card} key={memory.id}><Image source={{ uri: memory.image }} style={styles.image} /><View style={styles.body}><Text style={styles.title}>{memory.title}</Text><Text style={styles.meta}>{memory.location}  ·  {memory.date}</Text><Pressable onPress={() => remove(memory.id)}><Text style={styles.delete}>Delete memory</Text></Pressable></View></View>)}</View></ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: spacing.page, paddingTop: 58, backgroundColor: colors.sand, flexGrow: 1 }, headerRow: { position: 'relative' }, addButton: { position: 'absolute', right: 0, top: 0, padding: 10, borderRadius: 20, backgroundColor: colors.green }, addText: { color: '#fff', fontSize: 11, fontWeight: '800' }, form: { padding: spacing.card, marginBottom: 16, borderRadius: 14, backgroundColor: colors.paper }, input: { padding: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.line, borderRadius: 7, backgroundColor: '#fff' }, primaryButton: { alignItems: 'center', padding: 12, borderRadius: 7, backgroundColor: colors.green }, primaryText: { color: '#fff', fontWeight: '800' }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, card: { width: '48%', overflow: 'hidden', marginBottom: spacing.medium, borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.paper }, image: { width: '100%', height: 130 }, body: { padding: 11 }, title: { color: colors.ink, fontSize: 13, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 10, marginTop: 5 }, delete: { color: '#a65748', fontSize: 10, marginTop: 8 }, empty: { color: colors.muted, fontSize: 14 }, });
