import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { createTrip, deleteTrip, getTrips } from '../services/tripApi';
import ScreenHeader from '../components/ScreenHeader';
import TripCard from '../components/TripCard';
import { colors, spacing } from '../theme';

const emptyTrip = { tripName: '', destination: '', startDate: '', endDate: '' };

export default function TripsScreen() {
  const [trips, setTrips] = useState([]); const [form, setForm] = useState(emptyTrip); const [showForm, setShowForm] = useState(false); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState('');
  const loadTrips = async (refresh = false) => { try { if (!refresh) setIsLoading(true); setTrips(await getTrips()); } catch { setError('Unable to load trips.'); } finally { setIsLoading(false); } };
  useEffect(() => { void loadTrips(); }, []);
  const update = (name, value) => setForm((current) => ({ ...current, [name]: value }));
  const save = async () => { if (!form.tripName || !form.destination || !form.startDate || !form.endDate) { setError('Complete the trip name, destination and dates.'); return; } try { const saved = await createTrip({ ...form, budget: null, description: '' }); setTrips((current) => [saved, ...current]); setForm(emptyTrip); setShowForm(false); setError(''); } catch { setError('Unable to create this trip.'); } };
  const remove = async (id) => { try { await deleteTrip(id); setTrips((current) => current.filter((trip) => trip.id !== id)); } catch { setError('Unable to delete this trip.'); } };
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={isLoading} onRefresh={() => loadTrips(true)} tintColor={colors.green} />}><View style={styles.headerRow}><ScreenHeader eyebrow="YOUR JOURNEYS" title="My Trips" subtitle="All your adventures in one place." /><Pressable style={styles.addButton} onPress={() => setShowForm((current) => !current)}><Text style={styles.addText}>{showForm ? 'Close' : '+ Trip'}</Text></Pressable></View>{showForm && <View style={styles.form}><TextInput style={styles.input} placeholder="Trip name" value={form.tripName} onChangeText={(value) => update('tripName', value)} /><TextInput style={styles.input} placeholder="Destination" value={form.destination} onChangeText={(value) => update('destination', value)} /><View style={styles.row}><TextInput style={styles.halfInput} placeholder="Start date" value={form.startDate} onChangeText={(value) => update('startDate', value)} /><TextInput style={styles.halfInput} placeholder="End date" value={form.endDate} onChangeText={(value) => update('endDate', value)} /></View><Pressable style={styles.primaryButton} onPress={save}><Text style={styles.primaryText}>Create Trip</Text></Pressable></View>}{error && <Text style={styles.error}>{error}</Text>}{isLoading && <ActivityIndicator color={colors.green} />}{!isLoading && trips.length === 0 && <Text style={styles.empty}>No trips yet.</Text>}{trips.map((trip, index) => <View key={trip.id}><TripCard trip={trip} index={index} /><Pressable onPress={() => remove(trip.id)}><Text style={styles.delete}>Delete trip</Text></Pressable></View>)}</ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: spacing.page, paddingTop: 58, backgroundColor: colors.sand, flexGrow: 1 }, headerRow: { position: 'relative' }, addButton: { position: 'absolute', right: 0, top: 0, padding: 10, borderRadius: 20, backgroundColor: colors.green }, addText: { color: '#fff', fontSize: 11, fontWeight: '800' }, form: { padding: spacing.card, marginBottom: 16, borderRadius: 14, backgroundColor: colors.paper }, input: { padding: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.line, borderRadius: 7, backgroundColor: '#fff', color: colors.ink }, row: { flexDirection: 'row', gap: 8 }, halfInput: { flex: 1, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.line, borderRadius: 7, backgroundColor: '#fff' }, primaryButton: { alignItems: 'center', padding: 12, borderRadius: 7, backgroundColor: colors.green }, primaryText: { color: '#fff', fontWeight: '800' }, delete: { marginTop: -8, marginBottom: 14, color: '#a65748', fontSize: 11, textAlign: 'right' }, error: { color: '#a65748', marginBottom: 12 }, empty: { color: colors.muted } });